console.log("第一章(nodejs 内置对象与方法):");
console.log("");
require('./basic');
console.log("");
console.log("第二章(nodejs 手写一个简单的剪刀、石头与布猜拳游戏):");
console.log("");
require('./game');
console.log("");
console.log("第三章(commonjs 规范):");
console.log("");
require("./basic/commonjs");
console.log("");
console.log("第四章(使用 commonjs 规范规整剪刀、石头与布猜拳游戏):");
console.log("");
require("./game/commonjs");
console.log("");
console.log("第五章(nodejs 内置模块):");
console.log("");
require("./basic/module");
console.log("");
