console.log("第一章(nodejs 内置对象与方法):");
console.log("");
require("./basic");
console.log("");
console.log("第二章(nodejs 手写一个简单的剪刀、石头与布猜拳游戏):");
console.log("");
require("./game");
console.log("");
console.log("第三章(commonjs 规范):");
console.log("");
require("./basic/commonjs");
console.log("");
console.log("第四章(使用 commonjs 规范规整剪刀、石头与布猜拳游戏):");
console.log("");
require("./game/commonjs");
console.log("");
console.log("第五章(nodejs 内置模块):");
console.log("");
require("./basic/module");
console.log("");
console.log("第六章(非阻塞性 IO):");
console.log("");
require("./basic/nonBlock");
console.log("");
console.log("第七章(阻塞性 IO):");
console.log("");
require("./basic/block");
console.log("");
console.log("第八章(callback 回调函数):");
console.log("");
require("./basic/callback");
console.log("");
console.log("第九章(callback 回调函数-面试):");
console.log("");
require("./basic/callbackInterview");
console.log("");
console.log("第十章(事件循环 EventLoop):");
console.log("");
require("./basic/eventLoop");
console.log("");
console.log("第十一章(Promise - 面试):");
console.log("");
require("./basic/promiseInterview");
console.log("");
console.log("第十二章(Promise - 多公司面试):");
console.log("");
require("./basic/promiseMutiInterview");
console.log("");
console.log("第十三章(async/await - 面试):");
console.log("");
require("./basic/asyncAwaitInterview");
console.log("");
console.log("第十四章(http):");
console.log("");
require("./basic/http");
console.log("");
console.log("第十五章(httpServer):");
console.log("");
require("./basic/httpServer");
console.log("");
console.log("第十六章(使用 httpServer 改进剪刀、石头与布猜拳游戏并显示至 Web 页面中):");
console.log("");
require("./game/httpServer");
console.log("");
